site_name: Panini
repo_url: https://github.com/lwinterface/panini
repo_name: lwinterface/panini
nav:
    - Install: Install.md
    - Quickstart: Quickstart.md
    - What is NATS?: What_is_NATS.md
    - How Panini works?: 
        - First Step: How_first_step.md
        - Arguments panini app takes: How_arguments.md
        - Main functions of panini app : How_main_func.md
        - Incoming message strucutre: How_incoming_msg.md
    - Datatypes: Datatypes.md
    - Validation for incoming data: Validation_for_incoming_data.md
    - Middlewares: Middlewares.md
    - HTTP server: HTTP_server.md
    - WebSocket server: WebSocket_server.md
    - Balancer: Balancer.md
    - Middlewares: Middlewares.md
    - Monitoring application: Monitoring_application.md
    - Emulator - "time machine" debug: Emulator.md
    - Distributed tracing: Distributed_tracing.md
    - Deployment: Deployment.md
    - Changelog: Changelog.md
    - License: License.md
    - How to contribute: How_to_contribute.md
    - Testing: Testing.md
    - Logger: Logger.md
    - Examples: Examples.md
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: en    
theme:
  name: material
  features:
   - search.suggest
   - search.highlight
  palette:
    primary: light blue
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde