version: '3.6'

networks:
  internet:
    name: "internet"
    driver: bridge


services:
  nats-server:
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
    ports:
      - 4222:4222
      - 8222:8222
    image: nats:latest
    container_name: nats-server
    networks:
      - internet
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - internet
#  hotrod:
#    image: jaegertracing/example-hotrod:latest
#    ports:
#      - "8080:8080"
#    command: [ "all" ]
#    environment:
#      - JAEGER_AGENT_HOST=jaeger
#      - JAEGER_AGENT_PORT=6831
#    networks:
#      - internet
#    depends_on:
#      - jaeger
#  microservice1:
#    volumes:
#      - ./microservice1:/app/microservice1
#    build: microservice1/.
#    networks:
#      - internet
#    depends_on:
#      - nats-server
#  microservice2:
#    volumes:
#      - ./microservice2:/app/microservice2
#    build: microservice2/.
#    networks:
#      - internet
#    depends_on:
#      - nats-server
