version: 2.1
parameters:
  repo:
    type: string
    default: "panini"

working_directory: ~/<< pipeline.parameters.repo >>

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "3.8"
                - "3.9"

jobs:
  test:
    parameters:
      version:
        description: "python version tag"
        default: "3.8"
        type: string
    executor:
      name: executor-for-panini
      version: <<parameters.version>>
    steps:
      - checkout
      - install-requirements
      - run-tests
      - store-results

executors:
  executor-for-panini:
    parameters:
      version:
        type: string
        default: "3.8"
    docker:
      - image: python:<< parameters.version >>-slim-buster
      - image: nats

commands:
  install-requirements:
    steps:
      - run:
          name: Install requirements
          command: pip3 install pytest && pip3 install -r requirements/defaults.txt
  run-tests:
    steps:
      - run:
          name: Run tests
          command: |
            mkdir results
            timeout 300 python3 -m pytest --junitxml=results/out.xml || (echo "Doesn't finished succefully" && exit 1)
  store-results:
    steps:
      - store_test_results:
          path: results
